//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditAction
    {
        public AuditAction()
        {
            this.Audits = new HashSet<Audit>();
        }
    
        public int AuditTypeId { get; set; }
        public string AuditAction1 { get; set; }
    
        public virtual ICollection<Audit> Audits { get; set; }
    }
}
