//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContractEmployee
    {
        public int EmployeeRef4Id { get; set; }
        public int EmployedWith4Id { get; set; }
        [Required(ErrorMessage = "{0} is required.")]
        [Display(Name = "Contract Start Date", Prompt = "Enter Contract Start Date: ", Description = "Contract Start Date", ShortName = "Contract Start")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime ContractStartDate { get; set; }

        [Required(ErrorMessage = "{0} is required.")]
        [Display(Name = "Contract Stop Date", Prompt = "Enter Contract Stop Date: ", Description = "Contract Stop Date", ShortName = "Contract Stop")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime ContractStopDate { get; set; }
        public Nullable<int> ReasonForLeaving4Id { get; set; }

        [Required(ErrorMessage = "{0} is required.")]
        [Display(Name = "Fixed Contract Amount", Prompt = "Enter Fixed Contract Amount: ", Description = "Fixed Contract Amount", ShortName = "Contract Amount")]
        [Range(5, double.MaxValue, ErrorMessage = "{0} must be above 0")]
        public double FixedContractAmount { get; set; }

        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReasonForLeaving ReasonForLeaving { get; set; }
    }
}
