//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SeasonalEmployee
    {
        public int EmployeeRef3Id { get; set; }
        public int EmployedWith3Id { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Season Year", Prompt = "Enter Season Year: ", Description = "Season Year", ShortName = "Season Year")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime SeasonYear { get; set; }


        [Display(Name = "Piece Pay", Prompt = "Enter Piece Pay: ", Description = "Piece Pay", ShortName = "Piece Pay")]
        [Range(0, double.MaxValue, ErrorMessage = "{0} must be above 0")]
        public Nullable<double> PiecePay { get; set; }

        public Nullable<int> ReasonForLeaving3Id { get; set; }

        public Nullable<int> SeasonId { get; set; }

        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReasonForLeaving ReasonForLeaving { get; set; }
        public virtual Season Season { get; set; }
    }
}
