//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public Season()
        {
            this.SeasonalEmployees = new HashSet<SeasonalEmployee>();
        }
    
        public int SeasonId { get; set; }
        public string Season1 { get; set; }
    
        public virtual ICollection<SeasonalEmployee> SeasonalEmployees { get; set; }
    }
}
