//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonForLeaving
    {
        public ReasonForLeaving()
        {
            this.ContractEmployees = new HashSet<ContractEmployee>();
            this.FullTimeEmployees = new HashSet<FullTimeEmployee>();
            this.PartTimeEmployees = new HashSet<PartTimeEmployee>();
            this.SeasonalEmployees = new HashSet<SeasonalEmployee>();
        }
    
        public int ReasonForLeavingId { get; set; }
        public string ReasonForLeaving1 { get; set; }
    
        public virtual ICollection<ContractEmployee> ContractEmployees { get; set; }
        public virtual ICollection<FullTimeEmployee> FullTimeEmployees { get; set; }
        public virtual ICollection<PartTimeEmployee> PartTimeEmployees { get; set; }
        public virtual ICollection<SeasonalEmployee> SeasonalEmployees { get; set; }
    }
}
