//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PartTimeEmployee
    {
        public int EmployeeRef2Id { get; set; }
        public int EmployedWith2Id { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Date of Hire", Prompt = "Enter Date of Hire: ", Description = "Date of Hire", ShortName = "Date of Hire")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime DateOfHire { get; set; }

        [Display(Name = "Date of Termination", Prompt = "Enter Date of Termination: ", Description = "Date of Termination", ShortName = "Date of Termination")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> DateOfTermination { get; set; }

        [Display(Name = "Hourly Rate", Prompt = "Enter Hourly Rate: ", Description = "Hourly Rate", ShortName = "Hourly Rate")]
        [Range(5, double.MaxValue, ErrorMessage = "{0} must be above 0")]
        public Nullable<double> HourlyRate { get; set; }
        public Nullable<int> ReasonForLeaving2Id { get; set; }

        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReasonForLeaving ReasonForLeaving { get; set; }
    }
}
