//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TimeCard
    {
        public int EmployeeRef5Id { get; set; }
        public int EmployedWith5Id { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime WeekOf { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Mon { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Tue { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Wed { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Thu { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Fri { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Sat { get; set; }
        [Range(0.0, 24.0, ErrorMessage = "Must be greater than 0 and less than 24 hours")]
        public Nullable<decimal> Sun { get; set; }

        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
