//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Audits = new HashSet<Audit>();
            this.ContractEmployees = new HashSet<ContractEmployee>();
            this.EmployeeTypes = new HashSet<EmployeeType>();
            this.PartTimeEmployees = new HashSet<PartTimeEmployee>();
            this.SeasonalEmployees = new HashSet<SeasonalEmployee>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Pieces = new HashSet<Piece>();
            this.FullTimeEmployees = new HashSet<FullTimeEmployee>();
        }

        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "SIN/BN", Prompt = "Enter SIN/BN: ", Description = "Employee's SIN/BN")]
        public string SIN_BN { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Last Name", Prompt = "Enter First Name: ", Description = "Employee's Last Name")]
        [RegularExpression(@"^[-a-zA-Z' ]+$", ErrorMessage = "{0} may only include '-  a-Z A-Z.")]
        public string LastName { get; set; }

        [Display(Name = "First Name", Prompt = "Enter First Name: ", Description = "Employee's First Name")]
        [RegularExpression(@"^[-a-zA-Z' ]+$", ErrorMessage = "{0} name may only include '-  a-Z A-Z.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Display(Name = "Date of Birth", Prompt = "Enter Date of Birth: ", Description = "Date of Birth", ShortName = "Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime DateOfBirth { get; set; }

        public bool Active { get; set; }
        public bool Completed { get; set; }
        public virtual ICollection<Audit> Audits { get; set; }
        public virtual ICollection<ContractEmployee> ContractEmployees { get; set; }
        public virtual ICollection<EmployeeType> EmployeeTypes { get; set; }
        public virtual ICollection<PartTimeEmployee> PartTimeEmployees { get; set; }
        public virtual ICollection<SeasonalEmployee> SeasonalEmployees { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Piece> Pieces { get; set; }
        public virtual ICollection<FullTimeEmployee> FullTimeEmployees { get; set; }
    }
}
